stages:
  - build
  - deploy

build-job:       
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

deploy-job:     
  stage: deploy  
  script:
    - echo "Deploying application..."
    - sudo docker-compose up -d --build --force-recreate
    - echo "Application successfully deployed."
