before_script:
  - cd /home/docker/znanstvenakonferencija
deploying:
  stage: deploy
  only:
      - main
  
  script:
    - git reset --hard
    - git pull origin main
    - sudo docker-compose down
    - sudo docker-compose up -d --build --force-recreate
