before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - apt-get install -y -qq sshpass
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    
deploy_staging:
  type: deploy
  environment:
    name: production
    url: "$URL"
  script:
    - ssh "$SERVER_USER"@"$URL" "cd /home/docker/znanstvenakonferencija && git checkout main && git pull origin main && docker-compose up -d --build --force-recreate && exit"
  only:
    - main
