# Generated by Django 3.2.9 on 2021-11-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sekcija',
            fields=[
                ('sifSekcija', models.AutoField(primary_key=True, serialize=False)),
                ('nazivSekcija', models.CharField(max_length=50)),
            ],
        ),
    ]
