# Generated by Django 3.2.9 on 2021-11-07 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MK2ZK_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='korisnik',
            old_name='id',
            new_name='sifKorisnik',
        ),
    ]
