# Generated by Django 3.2.9 on 2021-11-07 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MK2ZK_App', '0002_rename_id_korisnik_sifkorisnik'),
    ]

    operations = [
        migrations.RenameField(
            model_name='korisnik',
            old_name='sifKorisnik',
            new_name='id',
        ),
    ]
