# Generated by Django 3.2.9 on 2021-11-07 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MK2ZK_App', '0003_rename_sifkorisnik_korisnik_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ustanova',
            old_name='adresa',
            new_name='adresaUstanova',
        ),
        migrations.RenameField(
            model_name='ustanova',
            old_name='drzava',
            new_name='drzavaUstanova',
        ),
        migrations.RenameField(
            model_name='ustanova',
            old_name='grad',
            new_name='gradUstanova',
        ),
    ]
