# Generated by Django 3.2.9 on 2021-11-10 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MK2ZK_App', '0004_auto_20211107_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rad',
            name='obrazlozenje',
        ),
        migrations.RemoveField(
            model_name='rad',
            name='ocjena',
        ),
        migrations.AddField(
            model_name='rad',
            name='pdf',
            field=models.FileField(upload_to='Radovi/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rad',
            name='radKorisnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MK2ZK_App.korisnik'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rad',
            name='radSekcija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MK2ZK_App.sekcija'),
            preserve_default=False,
        ),
    ]
