# Generated by Django 3.2.9 on 2021-11-12 12:25

import IzvorniKod.MK2ZK_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MK2ZK_App', '0005_auto_20211110_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rad',
            name='pdf',
            field=models.FileField(upload_to=IzvorniKod.MK2ZK_App.models.custom_directory),
        ),
    ]
