# Generated by Django 3.2.9 on 2021-11-12 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MK2ZK_App', '0006_alter_rad_pdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PoljaObrasca',
        ),
    ]
