# Generated by Django 3.2.9 on 2021-11-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MK2ZK_App', '0008_activedodatnapolja_dodatnapoljaobrasca'),
    ]

    operations = [
        migrations.AddField(
            model_name='dodatnapoljaobrasca',
            name='obavezan',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ActiveDodatnaPolja',
        ),
    ]
