# Generated by Django 3.2.9 on 2021-11-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MK2ZK_App', '0009_auto_20211112_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='dodatnapoljaobrasca',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
