# Generated by Django 3.2.9 on 2021-11-13 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MK2ZK_App', '0010_dodatnapoljaobrasca_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocjena',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('znacenje', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Uloga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='sekcija',
            old_name='nazivSekcija',
            new_name='naziv',
        ),
        migrations.RenameField(
            model_name='ustanova',
            old_name='adresaUstanova',
            new_name='adresa',
        ),
        migrations.RenameField(
            model_name='ustanova',
            old_name='drzavaUstanova',
            new_name='drzava',
        ),
        migrations.RenameField(
            model_name='ustanova',
            old_name='gradUstanova',
            new_name='grad',
        ),
        migrations.RenameField(
            model_name='ustanova',
            old_name='nazivUstanova',
            new_name='naziv',
        ),
        migrations.AddField(
            model_name='autor',
            name='OZK',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='korisnik',
            name='token',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rad',
            name='autori',
            field=models.ManyToManyField(to='MK2ZK_App.Autor'),
        ),
        migrations.AddField(
            model_name='sekcija',
            name='konferencijaSekcija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MK2ZK_App.konferencija'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Recenzija',
            fields=[
                ('sifRecenzija', models.AutoField(primary_key=True, serialize=False)),
                ('obrazlozenje', models.CharField(max_length=500)),
                ('ocjena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MK2ZK_App.ocjena')),
                ('rad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MK2ZK_App.rad')),
                ('recenzent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MK2ZK_App.korisnik')),
            ],
        ),
        migrations.CreateModel(
            name='DodatniPodatci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podatak', models.CharField(max_length=50)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MK2ZK_App.korisnik')),
                ('poljeObrasca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MK2ZK_App.dodatnapoljaobrasca')),
            ],
        ),
        migrations.AddField(
            model_name='korisnik',
            name='dodatniPodatak',
            field=models.ManyToManyField(through='MK2ZK_App.DodatniPodatci', to='MK2ZK_App.DodatnaPoljaObrasca'),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='vrstaKorisnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MK2ZK_App.uloga'),
        ),
    ]
