# Generated by Django 3.2.9 on 2021-11-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MK2ZK_App', '0011_auto_20211113_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rad',
            name='naslov',
            field=models.CharField(max_length=500),
        ),
    ]
