# Generated by Django 3.2.9 on 2021-11-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MK2ZK_App', '0012_alter_rad_naslov'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rad',
            old_name='recinziranBool',
            new_name='recenziranBool',
        ),
    ]
