# Generated by Django 3.2.9 on 2021-11-15 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MK2ZK_App', '0013_rename_recinziranbool_rad_recenziranbool'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipPoljaObrasca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='konferencija',
            name='rokAdmin',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='konferencija',
            name='rokRecenzenti',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AutorRad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OZK', models.BooleanField(default=False)),
                ('Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MK2ZK_App.autor')),
                ('Rad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MK2ZK_App.rad')),
            ],
        ),
        migrations.AlterField(
            model_name='dodatnapoljaobrasca',
            name='tipPolja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MK2ZK_App.tippoljaobrasca'),
        ),
        migrations.RemoveField(
            model_name='rad',
            name='autori'
        ),
        migrations.AddField(
            model_name='rad',
            name='autori',
            field=models.ManyToManyField(through='MK2ZK_App.AutorRad', to='MK2ZK_App.Autor'),
        ),
    ]
