# Generated by Django 4.0 on 2021-12-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MK2ZK_App', '0014_auto_20211115_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='rad',
            name='revizijaBool',
            field=models.BooleanField(default=False),
        ),
    ]
