# Generated by Django 3.2.9 on 2021-12-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MK2ZK_App', '0015_rad_revizijabool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='OZK',
        ),
        migrations.AddField(
            model_name='konferencija',
            name='rokPocPrijava',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='konferencija',
            name='rokPocRecenzija',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='korisnik',
            name='potvrdenBool',
            field=models.BooleanField(default=False),
        ),
    ]
