# Generated by Django 4.0 on 2021-12-15 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MK2ZK_App', '0016_auto_20211215_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='korisnikSekcija',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MK2ZK_App.sekcija'),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='korisnikUstanova',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MK2ZK_App.ustanova'),
        ),
    ]
