# Generated by Django 4.0 on 2021-12-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MK2ZK_App', '0017_alter_korisnik_korisniksekcija_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='konferencija',
            name='javniRadoviBool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='korisnik',
            name='activeBool',
            field=models.BooleanField(default=False),
        ),
    ]
