# Generated by Django 4.0 on 2021-12-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MK2ZK_App', '0018_konferencija_javniradovibool_korisnik_activebool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='odobrenBool',
            field=models.BooleanField(null=True),
        ),
    ]
