# Generated by Django 4.0 on 2021-12-21 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MK2ZK_App', '0019_alter_korisnik_odobrenbool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clanak',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('naslov', models.CharField(max_length=100)),
                ('tekst', models.CharField(max_length=1000)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MK2ZK_App.korisnik')),
            ],
        ),
    ]
