# Generated by Django 4.0 on 2021-12-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MK2ZK_App', '0020_clanak'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanak',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
