# Generated by Django 4.0 on 2021-12-21 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MK2ZK_App', '0021_clanak_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('naslov', models.CharField(max_length=100)),
                ('tekst', models.CharField(max_length=5000)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MK2ZK_App.korisnik')),
                ('konferencija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MK2ZK_App.konferencija')),
            ],
        ),
    ]
