# Generated by Django 3.2.9 on 2021-12-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MK2ZK_App', '0022_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korisnik',
            name='activeBool',
        ),
        migrations.AddField(
            model_name='korisnik',
            name='lastActive',
            field=models.DateTimeField(null=True),
        ),
    ]
