# Generated by Django 3.2.9 on 2021-12-28 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MK2ZK_App', '0023_auto_20211228_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='lastActive',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 28, 17, 30, 53)),
        ),
    ]
