# Generated by Django 4.0 on 2022-01-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MK2ZK_App', '0024_alter_korisnik_lastactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='lozinka',
            field=models.CharField(max_length=500),
        ),
    ]
