# Generated by Django 4.0 on 2022-01-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MK2ZK_App', '0025_alter_korisnik_lozinka'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='salt',
            field=models.BinaryField(null=True),
        ),
    ]
