# Generated by Django 4.0 on 2022-01-05 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MK2ZK_App', '0026_korisnik_salt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
