# Generated by Django 4.0 on 2022-01-10 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MK2ZK_App', '0027_delete_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='konferencija',
            name='rokAdmin',
        ),
    ]
